### ISSUE TITLE
Open API Document 명세 제안

### ISSUE THREAD

**Issue by J-Hoplin** [juintination/todo-api-server#1]
일반적으로 API에 대한 테스팅은 단순 Request가 아닌 Open API Specification을 해주는게 좋습니다. 단순히 백엔드 테스트 용도가 아닌 실제 프런트 엔드 개발자와의 협업을 할때 명세는 되게 중요한 역할을 합니다. 기존 Spring 프로젝트 Repository들에도 별도로 Open API 명세가 안되어있는거같아 이번 기회에 Open API Swagger를 활용해보는건 어떨까요?

Spring Boot에서 명세를 하는 방식은 대표적으로 세가지가 있습니다.

- Spring Swagger
- Spring Docs(Swagger 3)
- Postman OpenAPI Specification

Spring Docs Document: https://springdoc.org

**Comment by juintination** [comment]
추가하였습니다. 내용적으로 부족한 부분이 많겠지만 추후에 더 공부할 기회가 된다면 추가하도록 하겠습니다.

피드백 감사합니다 :)

**Comment by J-Hoplin** [comment]
응원합니다 ☺️
